[package]
name = "olivia_core"
version = "0.1.0"
authors = ["Will <will.s.medrano@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmidi = "4.0"