name: rust unit tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install jackd libjack0 libjack-dev liblilv-0-0 liblilv-dev  libsdl2-2.0-0 libsdl2-dev libportmidi0 libportmidi-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
